server.port: 8002


eureka:
  instance:
    # 【推荐】应用名称，当前集群的所有项目需要相同，否则无法进行关联
    ## 如果名称不同，无法显示到 available-replicas 中；会显示为2个独立的Application
    ## 如果名称相同的话，是一个Application中有多个服务
    # 此处配置优先于 spring.application.name
    ## 如果此处没有配置，则获取 spring.application.name 的值
    ## 如果两个都没有写，则显示 UNKNOWN
    ## 如果两个都写了，spring.application.name 的值会现在到 Status 列下，例如：UP (1) - localhost:eureka1:8001
    appname: eureka-server
    # 【必填】主机名或者当前服务域名，和appname搭配达到"一个Application中多个服务"
    hostname: eureka2.zhqy.com
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    #   register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    #   fetch-registry: false
    # 向指定的服务器进行注册
    service-url:
      # eureka 所有协议都是基于 restful 协议
      -defaultZone: http://eureka1.zhqy.com/eureka


spring:
  # 此值推荐使用 eureka.instance.appname 的值，不然在根据服务名称获取服务时无法正确获取
  application.name: ${eureka.instance.appname}